### ISSUE TITLE
Crash (?) on startup

### ISSUE THREAD

**Issue by Yoosk** [SamboyCoding/Thermal-Tinkering#1]
Instance seems to stop loading after error:
![2019-03-05 13-01-23-javaw](https://user-images.githubusercontent.com/4502802/53804071-6cf49000-3f3e-11e9-8d74-ea9584966f98.png)

ThermalTinkering: 1.12.2-2.0.0
Forge: 1.12.2-14.23.5.2811
Modpack: [All The Mods 3 - Remix 1.1.0](https://minecraft.curseforge.com/projects/all-the-mods-3-remix)
Full latest.log: https://p.teknik.io/4rj0c

**Comment by SamboyCoding** [comment]
Alright, thanks. It's because Thermal Expansion wants to load before  Ender IO, which wants to load before tinkers, and my mod wants to load after tinkers but after Thermal, which isn't possible. I'll change the way I do stuff.

**Comment by SamboyCoding** [comment]
Fixed in release 2.0.1
